### ISSUE TITLE
PI Bluetooth: sample python script for bluetooth simple application

### ISSUE THREAD

**Issue by hoangphan** [hoangphan/ProjectX#1]

**Comment by tri2510** [comment]
Using this tutorial: 
https://developer.xamarin.com/guides/android/

**Comment by hoangphan** [comment]
quote: 

> It turns out that choosing which machine to connect to and how to connect are the most difficult parts of Bluetooth programming

**Comment by hoangphan** [comment]
bluetooth.discover_devices()
this function shall query for **approximately 10 seconds**!!! so it is just for fun - not recommend to use in real server application.

**Comment by hoangphan** [comment]
successfully bringup the 2nd PI, and concurrently accessing 2 PI through local SSH.
see notes here 
https://github.com/hoangphan/ProjectX/wiki/Changing-Hostname-for-PI

**Comment by hoangphan** [comment]
successfully pair and communicate between 2 boards PI. see note as above. and 
https://github.com/hoangphan/ProjectX/wiki/Bluetooth-with-PI-zero-W
