### ISSUE TITLE
Understanding Xamarin Android

### ISSUE THREAD

**Issue by hoangphan** [hoangphan/ProjectX#2]
1. understanding fundamental of Xamarin application 

Read through tutorial

**Comment by hoangphan** [comment]
hihi

**Comment by tri2510** [comment]
Using this tutorial:
https://developer.xamarin.com/guides/android/

**Comment by tri2510** [comment]
On going:
https://developer.xamarin.com/guides/android/application_fundamentals/resources_in_android/part_3_-_alternate_resources/

**Comment by tri2510** [comment]
On going:
https://developer.xamarin.com/guides/android/application_fundamentals/activity_lifecycle/
